# Generated by Django 3.0.5 on 2020-05-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
