# Generated by Django 3.0.5 on 2020-05-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
    ]
